# Generated by Django 4.1 on 2022-11-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
    ]
