# Generated by Django 4.1 on 2022-11-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcla', '0002_alter_member_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to='Image'),
        ),
    ]
