# Generated by Django 4.1 on 2023-01-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webcla", "0005_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="website",
            new_name="url",
        ),
    ]
