# Generated by Django 4.1 on 2023-01-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webcla", "0008_rename_ratingue_commentandrating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="user",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="rating",
            old_name="score",
            new_name="rating",
        ),
    ]
