# Generated by Django 4.1 on 2023-01-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webcla", "0011_rating_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Image"),
        ),
    ]
